spring:
  profiles:
    group:
      db-console:
        - app
        - actuator
      db-real:
        - app
        - normal-mail
        - urgent-mail
        - actuator
      message-queue-console:
        - app
        - rabbitmq
        - actuator
      local-test:
        - app-local
        - actuator
      local-test-console:
        - app-local
        - actuator
    active: console
server:
  port:
    8080
