spring:
  profiles:
    group:
      console:
        - app
        - actuator
      real:
        - app
        - mail
        - actuator
      local-test:
        - app-local
        - actuator
    active: local-test
server:
  port:
    8080
