spring:
  mail:
    urgent:
      host: smtp.gmail.com
      port: 587
      username: yonggyu.jeong11@gmail.com
      password: ${URGENT_GMAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            timeout: 8000
            starttls:
              enable: true
