spring:
  mail:
    normal:
      host: smtp.gmail.com
      port: 587
      username: yonggyu.jeong10@gmail.com
      password: ${GMAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            timeout: 8000   #  5초 -> 8초 늘림
            starttls:
              enable: true
