spring:
  profiles:
    group:
      console:
        - app
        - actuator
      real:
        - app
        - normal-mail
        - urgent-mail
        - actuator
      local-test:
        - app-local
        - actuator
    active: real
server:
  port:
    8080
