spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

logging:
  level:
#    org.springframework: TRACE
#    java: TRACE
    org.springframework.amqp: DEBUG
    org.springframework.retry: DEBUG
    com.rabbitmq: DEBUG
