spring:
  profiles:
    group:
      console:
        - app
      real:
        - app
        - mail
      db:
        - app
      message-queue:
        - app
        - rabbitmq
    active: message-queue
server:
  port: 8081
