spring:
  profiles:
    group:
      console:
        - app
      real:
        - app
        - mail
      db:
        - app
      message-queue:
        - app
        - rabbitmq
      mock-mail:
        - app
        - mock-mail
    active: mock-mail
server:
  port: 8081
