spring:
  profiles:
    group:
      console:
        - app
        - mock-mail
      real:
        - app
        - mail
      db:
        - app
      message-queue:
        - app
        - rabbitmq
      mock-mail:
        - app
        - mock-mail
      minikube:
        - app-minikube
        - mock-mail
    active: minikube
server:
  port: 8081
